### ISSUE TITLE
Bug: Load Google authorization page

### ISSUE THREAD

**Issue by mattvanniekerk** [jeffream/csci-401-capstone#1]
Unrecognized Content-Security-Policy directive 'worker-src'.

**Comment by AlexVolcy** [comment]
Priority: 4, Severity: 4

**Comment by mattvanniekerk** [comment]
From the [MDN web docs page on _CSP: worker-src_](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src):

> The HTTP Content-Security-Policy (CSP) worker-src directive specifies valid sources for Worker, SharedWorker, or ServiceWorker scripts.

And:

> If this directive is absent, the user agent will first look for the child-src directive, then the script-src directive, then finally for the default-src directive, when governing worker execution.

worker-src is not compatible with Safari, which is the browser I use. This is why I saw the error message. It works on other browsers or falls back to other directives, and it does not cause any problems, so I have closed the issue.
