### ISSUE TITLE
Bug: Load 'Create Email Template' page

### ISSUE THREAD

**Issue by jtejada123** [jeffream/csci-401-capstone#15]
GET http://getbootstrap.com/2.3.2/assets/js/bootstrap.js net::ERR_NETWORK_CHANGED

**Comment by jtejada123** [comment]
Severity: 4, Priority: 4

**Comment by mattvanniekerk** [comment]
Not able to replicate this on Safari or Chrome.

**Comment by mattvanniekerk** [comment]
@jtejada123 originally found this issue and is now unable to replicate it. Perhaps it was fixed with npm update. Closing issue.
