### ISSUE TITLE
Bug: Load Templates Page

### ISSUE THREAD

**Issue by jtejada123** [jeffream/csci-401-capstone#2]
template-dashboard:189 Uncaught TypeError: Cannot set property 'innerHTML' of null
    at template-dashboard:189

**Comment by mattvanniekerk** [comment]
"TypeError: null is not an object (evaluating 'recommendation_button.innerHTML = '\<img src="/images/add_template.png" /\>'')"

No element with id "recommendation-button" exists

**Comment by jtejada123** [comment]
Severity: 4, Priority 4

**Comment by jtejada123** [comment]
Issue fixed

How: 
Adding an id to the image elements “recommendation-button” and “email-button”.
