### ISSUE TITLE
Bug: Recommendations disappear after a while, but templates persist

### ISSUE THREAD

**Issue by mattvanniekerk** [jeffream/csci-401-capstone#20]

**Comment by AlexVolcy** [comment]
Severity 3, Priority 3

**Comment by mattvanniekerk** [comment]
Page 3, point 5 of the Spring 2019 documentation states:

> Since the core functionality was only completed towards the very end of the semester, we 
were not able to conduct any long-term tests of the code. It seems like recommendations seem to get occasionally wiped after a while, but templates stay persistent. We are not sure what is causing this, or how severe of a problem it is, but this needs to be looked into.

**Comment by mattvanniekerk** [comment]
No one in the fall 2019 team has experienced this bug yet. We will continue to keep an eye out for it during development.
