### ISSUE TITLE
Bug: App crashes when the user tries to download/save the letter

### ISSUE THREAD

**Issue by mattvanniekerk** [jeffream/csci-401-capstone#22]

**Comment by AlexVolcy** [comment]
Severity: 2, Priority: 2

**Comment by mattvanniekerk** [comment]
This isn't an issue since we switched to @AlexVolcy's code right? @jtejada123

**Comment by jtejada123** [comment]
yes I'm gonna go ahead and close it

**Comment by mattvanniekerk** [comment]
This is actually still causing issues. I believe it's related to an update to one of the node modules, JSZip. 
> [...]
Error: The constructor with parameters has been removed in JSZip 3.0, please check the upgrade guide.
    at new JSZip (/Users/matt/CSCI 401/csci-401-capstone/letterOfRecGenerator/node_modules/jszip/lib/index.js:14:15)
    at /Users/matt/CSCI 401/csci-401-capstone/letterOfRecGenerator/routes/letter-preview.js:174:23
[...]

**Comment by mattvanniekerk** [comment]
I tried updating our code to work with JSZip 3 but received the error:

> Error: Docxtemplater doesn't handle JSZip version >=3, please use pizzip

PizZip is a fork of JSZip 2. I switched out JSZip for PizZip and now all is fine.
