### ISSUE TITLE
Bug: Click 'Preview Letter' Button on Recommendations Page

### ISSUE THREAD

**Issue by jtejada123** [jeffream/csci-401-capstone#6]
trix.js:15 [Deprecation] document.registerElement is deprecated and will be removed in M80, around February 2020. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.

**Comment by jtejada123** [comment]
Severity: 5 (only a warning, not an error), Priority 5

**Comment by mattvanniekerk** [comment]
I haven't been able to replicate this. I don't see trix.js in the dependencies or any use of document.registerElement in the project. Maybe it was fixed in an update to one or more node module. Do you still see the warning?

**Comment by jtejada123** [comment]
Just a warning so issue was closed. But the above warning says to  "switch 'document.registerElement' with 'window.customElements.define' ", sometime around February 2020.
